### ISSUE TITLE
Networking broken in version 1.1.0.0

### ISSUE THREAD

**Issue by devhawala** [livingcomputermuseum/Darkstar#10]
Hello,

while accessing the network works for version 1.0.0.1, this seems to be broken in version 1.1.0.0:
- send ethernet packets works,
- but received packets are not relayed to the emulator.

The necessary line appears to have been removed accidentally along with some logging line cleanups during commit "Small tweaks, updated readme", the relevant lost statement is
```
_callback(new System.IO.MemoryStream(e.Packet.Data));
```
in (deleted) line 205 of `HostEthernet.cs`, method `ReceiveCallback`.

However version 1.0.0.1 still has a problem with received packets: the system running in the emulator seems to expect 2 additional words per packet, as
- packets having the correct ethernet length for an IDP packet (IDP length + 14 bytes for the ethernet addressing, with min. 60 bytes for an ethernet packet) are mostly ignored,
- but packets are seen and processed if the ethernet packet has 2 extra 16 bit words (with zero).

Dodo now has an option for adding the extra 2 words, but this should better be fixed in Darkstar...

Regards,
Hans

**Comment by livingcomputermuseum** [comment]
Thanks for the bug report, and thanks for catching that erroneous deletion.  I'll take a look at it this evening.

**Comment by livingcomputermuseum** [comment]
At long last I've reverted the erroneously deleted line, and I've updated the binaries on the release page for v1.1.0.0.  I'm curious if the packet length hack is still required, please let me know if it is and if you're able to provide sample packets that reproduce the problem.  (I'm curious if this only occurs for small (~60 byte) packets or if others are similarly affected...).

Sorry for the extreme delay here.

**Comment by devhawala** [comment]
Hello,

thanks for the update, networking basically works again in the new version 1.1.0.0 of Darkstar.

However: the packet length hack in Dodo is still necessary (in the sample `dodo.properties` at the end, this is the option: `ether.useDarkstarWorkaround = true`).

I tested this with the XDE 5.0 disk of Darkstar and the current Dodo distribution. The problem of ignored packets is quite easy to spot by observing what happens at MP code 0937 when time is queried from the network. The configuration of Darkstar in the Configuration dialog was to use the current time (19. november 2020), whereas Dodo is configured to use the 28 years back shift.

When running Dodo with the option `ether.useDarkstarWorkaround = true` and observing network traffic with Dodo Netspy, there is only 1 (one) time request packet coming from Darkstar and one response packet at MP 0937 before XDE continues to boot. The time in XDE can then be checked after the boot completed by hitting the "Time" menu item of an "Empty window", which inserts the current time in the file window: this inserts 19-Nov-92 in this case.

Removing the option `ether.useDarkstarWorkaround = true` from the `dodo.properties` file and restarting Dodo, then restarting Darkstar/XDE will result in 9 cycles of time request + response packets during the MP 0937 phase, which takes longer before booting continues. The current time inserted in a file window like described above is then 10-Nov-20, meaning that the time was not set from the network responses during MP 0937.

Just as speculation: i suppose the network microcode expects a complete ethernet frame, which has a 4 byte "frame check sequence" after the payload. This frame check sequence is in fact a checksum,  by pure coincidence with 2 words length. Luckily the network microcode does not really verify the checksum, as Dodo always sends 2 zero words if the option `ether.useDarkstarWorkaround = true` is used, which is almost never the correct checksum...

So the simplest thing to do would be to simply add 2 words (value zero) to a packet received through the packet capture layer (or somehow convice the packet capture library to also deliver the original 2 frame check words).

Cheers, Hans

And here is the `dodo.properties` file used for the experiment:

```
# begin Darkstar specific
#
authSkipTimestampChecks = true
spp.sendingTimeGap = 75
ether.useDarkstarWorkaround = true
#
# end Darkstar specific

networkNo = 74
machineId = 10-00-BB-10-11-01
useChecksums = true

# time zone parameter for the time service
# e.g. for local time = CEST (+1hr with DST)
timeService.localTimeOffsetMinutes = 60

# shift date if required, e.g. back 28 years (2018 => 1990)
timeService.daysBackInTime = 10227

# clearinghouse service and database
# default: organizationName = hawala
# default: domainName = dev
chsDatabaseRoot = ./chs-database

# how to generate strong keys
# (XDE does not rejected neither 'true' nor 'false', so it is unclear which is right) 
strongKeysAsSpecified = true

# print service
printService.name = poseidon:dev:hawala
printService.outputDirectory = ./poseidon
printService.paperSizes = a4, usLetter
printService.disassembleIp = true
printService.ip2PsProcFilename = ./poseidon/res/IPPROC.PS
printService.psPostprocessor = ./poseidon/res/postprocess-ps.sh

# begin file services
fileService.0.name = fs1:dev:hawala
fileService.0.volumePath = ./fs1
```
