### ISSUE TITLE
Where is the darkstarsetup.msi?

### ISSUE THREAD

**Issue by thecondons** [livingcomputermuseum/Darkstar#2]
Josh, 
This project is awesome! 

Maybe my lack of github experience is showing, but the instructions in the README.md you provided say that to install this 'Double-click the installer file, named "DarkstarSetup.msi" and follow the on-screen instructions'. Only trouble is that I cannot locate the '.msi' file to install in github. Please enlighten me. (and keep up the great work)!
Thanks

**Comment by livingcomputermuseum** [comment]
Precompiled binaries and installers can be found on the Releases page, see: https://github.com/livingcomputermuseum/Darkstar/releases.  Thanks!

**Comment by thecondons** [comment]
Thanks so much for answering! 
Might be good to add this to the README file.
I can hardly wait to try it out! 
All the Best...
