### ISSUE TITLE
Darkstar crashes on MP 7700 (file check)

### ISSUE THREAD

**Issue by iblowmymind** [livingcomputermuseum/Darkstar#5]
For note, I am using the Bitsavers prebuilt hard disk images. (VP 2.0)
While booting, Darkstar suddenly crashes in the middle of a file check sequence (MP 7500-7600-7700). There is no log or note attached to it. This issue affects the latest version, in a Wine environment. I am using a Mac.

By the way, I love your emulator! I love the Xerox 8010 and 6085 environments in general, such a shame the 8010/6085 wasn't that common to see. (Been looking for factoring passwords, haven't found one except these.) It'd be also very nice if a 6085 emulator was made.

**Comment by iblowmymind** [comment]
Update: Sometimes it works, sometimes crashes. I don't know.

**Comment by livingcomputermuseum** [comment]
Thanks for the report -- I haven't tried running this under Wine but I can give it a shot -- what version of Wine and MacOS are you running?  Do you get any diagnostics at all (stack trace, etc.)?

**Comment by iblowmymind** [comment]
I am running this wine 1.8.6 bundled inside WineBottler, and macOS 10.14.2. No diagnostic reports at all on Wine.log. It just says "Process exited with a Mono runtime loaded." Maybe it's a problem caused by wine-mono? It just randomly exits at a random time.
