### ISSUE TITLE
Some questions & feature requests

### ISSUE THREAD

**Issue by iblowmymind** [livingcomputermuseum/Darkstar#8]
This is my second time creating an issue i hope i'm not being annoying-
Since this emulator was released, i was really interested in it and I've been following it for a while now. Seriously, great work!

(also, I've swapped to a Windows PC a few months ago, and Darkstar runs just fine!)

I've recently tried installing XDE 5.0 from the ImageDisk versions of the XDE provided in Bitsavers. It installs and boots just fine, and I'd say I got really familiar with the Tajo interface, however something i noticed was that the compiler and the binder commands didn't work, and the Command Central was missing. 

In the XDE documentation, these are mentioned as being integrated to the system. But somehow they weren't installed. Which got me automatically thinking that maybe the image was corrupted or missing something. But I couldn't check if that was true because the only other XDE 5 was supplied in either DMK or RAW images, and Darkstar supported neither of them. I tried to find a way of converting the files into IMD, but both Dunfield's IMD program (which I used with DOSbox) and SAMDisk said that they didn't support the DMK images. Dunfield's dmk2imd just rejected the DMK, and SAMDisk gave a bunch of warnings saying that the headers for every sector is wrong/corrupted, and gave an IMD file, but checking the file with XDE's Floppy List softlocked the system, so I realised that the IMD file was possibly blank. So, maybe the DMK versions of the XDE contains the files required for compilation. Which brings me to my questions: 
1. Is Darkstar going to support reading from DMK images in the future?
2. If it isn't, is there any way of converting the DMK images to IMD?

And, something else I noticed was that the User.cm refers to the version being XDE 4.0. Hmm.
I don't think my system information is necessary, since the emulator runs perfectly, but i'm on Windows 10 Home.

Thanks!

**Comment by livingcomputermuseum** [comment]
Hi -- Apologies for the delayed response.

Unfortunately, the XDE 5.0 Mesa compilers are simply unavailable -- no copy of them on floppy media has yet been archived to my knowledge.

DMK support for Darkstar is unlikely.  The DMK images on Bitsavers were captured with dmklib (see http://dmklib.brouhaha.com/) and as you've noted, something's weird about them.  Eric's dmk2raw tool is able to convert them to a raw disk image, and you can convert them to IMD format using the bin2imd tool included with Dunfield's ImageDisk. Invoke it via:

bin2imd <raw file> <output file> starraw.b2i

Where starraw.b2i is a text file containing:

0 N=77 SS1=128 SS0=256 DM1=0 DM0=3 SM0=1-26 SM1=1-26 /2
1 SS=512 DM=3 SM=1-15 /2

This will create a properly formatted IMD image for use with DarkStar.  Yes, this is a pain in the neck, and I apologize.

**Comment by iblowmymind** [comment]
Ah, thank you for your reply!
It's kinda sad that such a cool piece of technology can get lost if it's not well-archived, but well, who from PARC or somewhere else would've thought that people from 40 years later would be interested in their technology?

Anyways, I'll sure try converting the images with the solution you mentioned above, and thanks for helping!
