### ISSUE TITLE
No DarkstarSetup.msi or Darkstar-mono.zip files

### ISSUE THREAD

**Issue by josgrp** [livingcomputermuseum/Darkstar#9]
Both files are missing.
So it's impossible to install Darkstar.

**Comment by livingcomputermuseum** [comment]
Please check the Releases page: https://github.com/livingcomputermuseum/Darkstar/releases

**Comment by josgrp** [comment]
Thank you very much for your mail.
It seems I don’t quite understand the way Github works.
I really tried everything but couldn’t find this page.

Verzonden vanuit Mail voor Windows 10

Van: Living Computers: Museum+Labs
Verzonden: vrijdag 26 juni 2020 18:43
Aan: livingcomputermuseum/Darkstar
CC: josgrp; Author
Onderwerp: Re: [livingcomputermuseum/Darkstar] No DarkstarSetup.msi orDarkstar-mono.zip files (#9)

Please check the Releases page: https://github.com/livingcomputermuseum/Darkstar/releases
